### ISSUE TITLE
`dictToFoam` executable binary file

### ISSUE THREAD

**Issue by iydon** [iydon/of.yaml#3]
# Rust
```toml
[package]
name = "dictToFoam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compress-tools = "0.12.2"
yaml-rust = "0.4"
```
